version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Clone submodules
          command: |
            git submodule sync
            git submodule update --init
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "conf.py" }}
      - run:
          name: Install Nikola
          command: sudo pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "conf.py" }}
          paths:
            - "$HOME/.cache/pip"
      - run:
          name: Build site with Nikola
          command: nikola build
      - store_artifacts:
          path: ./output/
  build_deploy:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Clone submodules
          command: |
            git submodule sync
            git submodule update --init
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "conf.py" }}
      - run:
          name: Install Nikola
          command: sudo pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "conf.py" }}
          paths:
            - "$HOME/.cache/pip"
      - run:
          name: Build site with Nikola
          command: nikola build
      - run:
          name: Deploy to GitHub Pages
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git config --global user.name 'CirclCI'
              git config --global user.email 'circleci@invalid'
              git pull --all
              git remote add deploy https://${GITHUB_TOKEN}@github.com/Quansight-Labs/quansight-labs-site.git
              nikola github_deploy -m 'Nikola auto deploy [ci skip]'
            fi

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - build_deploy:
          context: org-global
          filters:
            branches:
              only:
                - master
